# CUDA
cuda_devices: '0'

# dataset
dataset:
  data_root: 'dataset/house_processed'
  augment_data: false
  max_faces: 500

# model
load_model: 'ckpt_root_2/MeshNet_best.pkl'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
  mask_ratio: 0.95
  dropout: 0.5
  num_classes: 40

# test config
batch_size: 128
retrieval_on: true
